### PR TITLE
My way of helping the community 

### PR DESCRIPTION
**Pull request by Shreenidhi1999**

### CODE REVIEW

**Comment by Caceresenzo** [comment]
A lot of cells have errors in it
Could you clear them please?

EDIT: Typos

**Comment by Caceresenzo** [comment]
As well as remove the empty cells

**Comment by Shreenidhi1999** [comment]
Ok sir, I will editing those typos and remove the empty cells.

**Comment by Shreenidhi1999** [comment]
Sir,
I have attached a zipped file of a notebook, please check.
Thanks and Regards,
Shreenidhi Hipparagi
[Datacrunch.zip](https://github.com/datacrunch-com/datacrunch-notebooks/files/6458986/Datacrunch.zip)

**Comment by Caceresenzo** [comment]
This is better thanks
I know its a lot of back and forth, but could you rename it and put in the quickstarter directory please?
(rename it in something meaningful)

Please
Thanks

**Comment by Caceresenzo** [comment]
(and there is still the first cell which hasn't been cleared :)  )

**Comment by Caceresenzo** [comment]
@jeheran is the naming good for you?
or is `Datacrunch.ipynb` too generic?

**Comment by Shreenidhi1999** [comment]
Sir, I have renamed the .ipynb file. Please check if any changes are to be made.

**Pull request merged**
